console.log([] + [])
console.log({} + [])
console.log([] + {})
console.log({} + {})

console.log(0 == '')
console.log(0 == false)
console.log(0 == undefined)
console.log(0 == null)
console.log('' == undefined)
console.log('' == null)
console.log(false == null)

console.log(undefined == null)
console.log(null == '')
console.log(null == 0)
